/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jurgenn
 */
public class interfazEquipo_RUD extends javax.swing.JFrame {

    ControladorPrincipal control;
    Vector<String> copiaCodigosEquipo;

    /**
     * Creates new form interfazEquipo_RUD
     *
     * @param control
     */
    public interfazEquipo_RUD(ControladorPrincipal control) {
        initComponents();
        cargarEquipos();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rudEquipo_tabla = new javax.swing.JTable();
        rudEquipo_actualizar = new javax.swing.JButton();
        rudEquipo_borrar = new javax.swing.JButton();
        rudEquipo_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Interfaz Equipo Read, Update y Delete");

        rudEquipo_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rudEquipo_tabla);

        rudEquipo_actualizar.setText("Actualizar");
        rudEquipo_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rudEquipo_actualizarActionPerformed(evt);
            }
        });

        rudEquipo_borrar.setText("Borrar");
        rudEquipo_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rudEquipo_borrarActionPerformed(evt);
            }
        });

        rudEquipo_salir.setText("Salir");
        rudEquipo_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rudEquipo_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(rudEquipo_actualizar)
                .addGap(136, 136, 136)
                .addComponent(rudEquipo_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rudEquipo_salir)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rudEquipo_actualizar)
                    .addComponent(rudEquipo_borrar)
                    .addComponent(rudEquipo_salir))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarEquipos() {
        try {
            //Inicializa el vector con codigos de equipo
            copiaCodigosEquipo = new Vector<>();

            //Hago conexion
            Connection connection = Conexion.getConexion();
            Statement statement = connection.createStatement();

            //Realiza el query
            String query = "SELECT * FROM EQUIPO";
            ResultSet output = statement.executeQuery(query);

            //Obtengo los metadatos y nombres de columnas
            ResultSetMetaData metaDatos = output.getMetaData();
            int index = metaDatos.getColumnCount();

            Vector nombreColumnas = new Vector();
            for (int i = 1; i <= index; i++) {
                nombreColumnas.add(metaDatos.getColumnLabel(i));
            }

            //Obtengo las tuplas en un vector que contiene vectores
            Vector filas = new Vector();
            while (output.next()) {
                Vector tupla = new Vector();
                for (int i = 1; i <= index; i++) {
                    tupla.add(output.getString(i));
                }
                filas.add(tupla);
                copiaCodigosEquipo.add((String) tupla.get(0));
            }

            //Muestro los resultados
            DefaultTableModel modelo = (DefaultTableModel) this.rudEquipo_tabla.getModel();
            modelo.setDataVector(filas, nombreColumnas);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla de Equipos");
        }
    }

    private void rudEquipo_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rudEquipo_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_rudEquipo_salirActionPerformed

    private void rudEquipo_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rudEquipo_actualizarActionPerformed
        control.actualizarEquipo(copiaCodigosEquipo.get(rudEquipo_tabla.getSelectedRow()),
                (String) rudEquipo_tabla.getModel().getValueAt(rudEquipo_tabla.getSelectedRow(), 0),
                (String) rudEquipo_tabla.getModel().getValueAt(rudEquipo_tabla.getSelectedRow(), 1),
                (String) rudEquipo_tabla.getModel().getValueAt(rudEquipo_tabla.getSelectedRow(), 2),
                (String) rudEquipo_tabla.getModel().getValueAt(rudEquipo_tabla.getSelectedRow(), 3));
        this.cargarEquipos();
    }//GEN-LAST:event_rudEquipo_actualizarActionPerformed

    private void rudEquipo_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rudEquipo_borrarActionPerformed
        try {
            control.borrarEquipo((String) rudEquipo_tabla.getModel().getValueAt(rudEquipo_tabla.getSelectedRow(), 0));
            JOptionPane.showMessageDialog(null, "Equipo borrado correctamente");
            this.cargarEquipos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al borrar el equipo");
        }
    }//GEN-LAST:event_rudEquipo_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rudEquipo_actualizar;
    private javax.swing.JButton rudEquipo_borrar;
    private javax.swing.JButton rudEquipo_salir;
    private javax.swing.JTable rudEquipo_tabla;
    // End of variables declaration//GEN-END:variables
}
